/**
 * Cross-language regression test.
 *
 * The extension re-implements the detection logic in JavaScript so scanning can
 * run inside the browser. Two implementations of the same rules will drift
 * apart unless something checks them.
 *
 * cases.json and doc_cases.json are generated by running the *Python* detectors
 * over the labeled evaluation dataset. This asserts the JavaScript ports
 * produce identical scores, risk bands, and findings for every case. Any
 * divergence fails the build.
 *
 *   node extension/test/run_tests.js
 */

const fs = require("fs");
const path = require("path");
const { checkEmail, riskBand } = require("../detector.js");
const { evaluateDocument, documentRiskBand } = require("../docdetector.js");

const load = (f) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, f), "utf8"));

const failures = [];

function compare(id, got, expected) {
  const problems = [];
  if (got.score !== expected.expected_score) {
    problems.push(`score ${got.score} != python ${expected.expected_score}`);
  }
  if (got.band !== expected.expected_band) {
    problems.push(`band ${got.band} != python ${expected.expected_band}`);
  }
  const a = JSON.stringify(got.titles);
  const b = JSON.stringify(expected.expected_titles);
  if (a !== b) {
    problems.push(`findings differ\n        js:     ${a}\n        python: ${b}`);
  }
  if (problems.length) failures.push({ id, problems });
  return problems.length === 0;
}

function runSuite(title, cases, runner) {
  console.log(`\n${title}`);
  console.log("-".repeat(66));
  let passed = 0;
  for (const c of cases) {
    const got = runner(c);
    const ok = compare(c.id, got, c);
    if (ok) passed += 1;
    const mark = ok ? "ok  " : "FAIL";
    console.log(`  ${mark}  ${c.id.padEnd(30)} score ${String(c.expected_score).padStart(3)}  ${c.expected_band}`);
    if (!ok) {
      failures.find((f) => f.id === c.id).problems
        .forEach((p) => console.log(`        ${p}`));
    }
  }
  console.log(`  ${passed}/${cases.length} match the Python implementation`);
  return passed;
}

console.log("Cross-language parity: JavaScript ports vs. Python reference");
console.log("=".repeat(66));

const emailCases = load("cases.json");
const emailPassed = runSuite("Phishing email detector", emailCases, (c) => {
  const { findings, score } = checkEmail(c.text, c.sender);
  return { score, band: riskBand(score).band,
           titles: findings.map((f) => f.title) };
});

const docCases = load("doc_cases.json");
const docPassed = runSuite("Document fraud detector", docCases, (c) => {
  const { findings, score } = evaluateDocument(
    c.text, c.metadata, c.vendors, c.claims_original);
  return { score, band: documentRiskBand(score).band,
           titles: findings.map((f) => f.title) };
});

const total = emailCases.length + docCases.length;
const passed = emailPassed + docPassed;

console.log("\n" + "=".repeat(66));
console.log(`${passed}/${total} cases match the Python implementation exactly.`);
process.exit(failures.length ? 1 : 0);
