/**
 * Cross-language regression test.
 *
 * The extension re-implements check_email() in JavaScript so detection can run
 * inside the browser. Two implementations of the same rules will drift apart
 * unless something checks them.
 *
 * cases.json is generated by running the *Python* detector over a labeled set
 * (see the generator command in the extension README). This asserts the
 * JavaScript port produces the identical score, risk band, and set of findings
 * for every case. Any divergence fails the build.
 *
 *   node extension/test/run_tests.js
 */

const fs = require("fs");
const path = require("path");
const { checkEmail, riskBand } = require("../detector.js");

const cases = JSON.parse(
  fs.readFileSync(path.join(__dirname, "cases.json"), "utf8"));

let passed = 0;
const failures = [];

for (const c of cases) {
  const { findings, score } = checkEmail(c.text, c.sender);
  const band = riskBand(score).band;
  const titles = findings.map((f) => f.title);

  const problems = [];
  if (score !== c.expected_score) {
    problems.push(`score ${score} != python ${c.expected_score}`);
  }
  if (band !== c.expected_band) {
    problems.push(`band ${band} != python ${c.expected_band}`);
  }
  const a = JSON.stringify(titles);
  const b = JSON.stringify(c.expected_titles);
  if (a !== b) {
    problems.push(`findings differ\n      js:     ${a}\n      python: ${b}`);
  }

  if (problems.length) {
    failures.push({ id: c.id, problems });
  } else {
    passed += 1;
  }
}

console.log("Cross-language parity: JavaScript port vs. Python reference");
console.log("=".repeat(62));
for (const c of cases) {
  const failed = failures.find((f) => f.id === c.id);
  const mark = failed ? "FAIL" : "ok  ";
  console.log(`  ${mark}  ${c.id.padEnd(26)} score ${String(c.expected_score).padStart(3)}  ${c.expected_band}`);
  if (failed) failed.problems.forEach((p) => console.log(`        ${p}`));
}
console.log("=".repeat(62));
console.log(`${passed}/${cases.length} cases match the Python implementation exactly.`);

process.exit(failures.length ? 1 : 0);
